title: "Orson Lee"
description: "" # Leave this blank to prevent double name
theme: minima

header_pages:
  - index.md

minima:
  social_links:
    - platform: github
      user_url: "https://github.com/osnlz1694"
    - platform: linkedin
      user_url: "https://linkedin.com/in/osnlz1694"
