# Site-wide settings
# ------------------
title: Portfolio
author:
   name: Orson Lee
   email: osnlz1694@berkeley.edu

# The `>` after `description:` means to ignore line-breaks until next key. If you wish to omit the line-break after the end of text, use `>-` instead.
description: >
   Write an awesome description for your new site here. You can edit this line
   in _config.yml. It will appear in your document head meta (for Google search
   results) and in your feed.xml site description.

theme: minima
