title: "Orson Lee"
description: ""  # Leave empty to avoid repeated text
theme: minima

header_pages:
  - index.md
  - contact.md

minima:
  social_links:
    - platform: github
      user_url: "https://github.com/osnlz1694"
    - platform: linkedin
      user_url: "https://linkedin.com/in/osnlz1694"
